version: "3.8"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile-backend
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./backend:/app
    networks:
      - my-network

networks:
  my-network:
    name: my-network
