version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    networks:
      - my-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - my-network

networks:
  my-network:
    name: my-network